apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankweb
  labels:
    app: bankweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankweb
  template:
    metadata:
      labels:
        app: bankweb
    spec:
      containers:
        - name: bankweb
          image: bankweb
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bankweb
  labels:
    app: bankweb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bankweb
  sessionAffinity: None
status:
  loadBalancer: {}